### ISSUE TITLE
剪映字幕转换兼容mac 上py 2的版本

### ISSUE THREAD

**Issue by czkoko** [fukco/DaVinciResolveScript#1]
#修改了几处，没学过py，找资料瞎改的
reload(sys)
sys.setdefaultencoding('utf-8')

    f = open(json_file, mode="r")

    srt_file = os.path.join(srt_folder, project_name + '_' + time_str +'.srt')
    f = open(srt_file, "w+")
    i = 1

    sub_text = str(text["content"])
    f.writelines([str(i) + "\n" + start_time + " --> " + end_time + "\n" + sub_text + "\n" + "\n"])

**Comment by fukco** [comment]
> #修改了几处，没学过py，找资料瞎改的
> reload(sys)
> sys.setdefaultencoding('utf-8')
> 
> ```
> f = open(json_file, mode="r")
> 
> srt_file = os.path.join(srt_folder, project_name + '_' + time_str +'.srt')
> f = open(srt_file, "w+")
> i = 1
> 
> sub_text = str(text["content"])
> f.writelines([str(i) + "\n" + start_time + " --> " + end_time + "\n" + sub_text + "\n" + "\n"])
> ```

抱歉，刚看到，我改下，好了通知你

**Comment by fukco** [comment]
代码已经修改了，应该没问题了
