### ISSUE TITLE
没有后续步骤。。。安装压缩包后，后续可以通过点击【工作区/脚本/Script Installer】执行

### ISSUE THREAD

**Issue by newwying** [fukco/DaVinciResolveScript#3]

**Comment by fukco** [comment]
没看懂你要表达的，是安装无效果？如果是破解版的话，请手动安装，如果不是我说的这个问题，麻烦重新描述下

**Comment by newwying** [comment]
> 没看懂你要表达的，是安装无效果？如果是破解版的话，请手动安装，如果不是我说的这个问题，麻烦重新描述下

应该是这个原因，不过手动安装后，松下S5M2和索尼ZV1的视频素材中ISO和快门速度的数据偏移到白平衡去了，似乎添加了一行后恢复正常，这是为啥呀？fields_list = [
    ("IsSupportMedia", c_bool),
    ("Camera Type", c_char_p),
    ("Camera Manufacturer", c_char_p),
    ("Camera Serial #", c_char_p),
    ("Camera ID", c_char_p),
    ("Camera Notes", c_char_p),
    ("Camera Format", c_char_p),
    ("Media Type", c_char_p),
    ("Time-Lapse Interval", c_char_p),
    ("Camera FPS", c_char_p),
    ("Shutter Type", c_char_p),

    #("Shutter Angle", c_char_p),
    ("Shutter Speed", c_char_p),

    # ("Shutter", c_char_p),
    ("ISO", c_char_p),
    ("White Point (Kelvin)", c_char_p),
    ("White Balance Tint", c_char_p),
    ("Camera Firmware", c_char_p),
    ("Lens Type", c_char_p),
    ("Lens Number", c_char_p),
    ("Lens Notes", c_char_p),
    ("Camera Aperture Type", c_char_p),
    ("Camera Aperture", c_char_p),
    ("Focal Point (mm)", c_char_p),
    ("Distance", c_char_p),
    ("Filter", c_char_p),
    ("ND Filter", c_char_p),
    ("Compression Ratio", c_char_p),
    ("Codec Bitrate", c_char_p),
    ("Sensor Area Captured", c_char_p),
    ("PAR Notes", c_char_p),
    ("Aspect Ratio Notes", c_char_p),
    ("Gamma Notes", c_char_p),
    ("Color Space Notes", c_char_p)]


然后松下的元数据好少，有办法改善吗。然后DJI的都读取不了，可以如何添加吗？🙇‍

**Comment by fukco** [comment]
DJI的我看过没啥可读取的数据，所以代码没处理，是对照exiftool看的，如果有确定字段可以跟我讲提供下截图我好确定哪些；
松下我处理过一些，也受限于我手上测试素材，当然也受限达芬奇metadata展示字段限制不是能读到的都有地方展示，可以提供一小段素材我解析看看；
至于你说的偏移的这个问题晚些时候我用电脑看下什么情况，这个没人反馈过

**Comment by fukco** [comment]
看了你发的，居然是用的python的代码，python的代码没有再维护了，用lua版本的，一些奇奇怪怪的问题可能就不会出现了^^

**Comment by newwying** [comment]
> 看了你发的，居然是用的python的代码，python的代码没有再维护了，用lua版本的，一些奇奇怪怪的问题可能就不会出现了^^

好吧的确。🙇‍
